# This is a basic workflow to help you get started with Actions

name: CI

on:
   workflow_dispatch:

# Controls when the workflow will run
#on:
#   Triggers the workflow on push or pull request events but only for the "ci-tests-workflow" branch
#  push:
#    branches: [ "ci-tests-workflow" ]
#  pull_request:
#    branches: [ "ci-tests-workflow" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      ROS_DISTRO: noetic
#      ROS_CI_DESKTOP: "`lsb_release -cs`"  # e.g. [trusty|xenial|...]
#      CI_SOURCE_PATH: $(pwd)
#      ROSINSTALL_FILE: $CI_SOURCE_PATH/dependencies.rosinstall
#      CATKIN_OPTIONS: $CI_SOURCE_PATH/catkin.options
#      ROS_PARALLEL_JOBS: '-j8 -l6'
#      # Set the python path manually to include /usr/-/python3/dist-packages
#      # as this is where apt-get installs python packages.
#      PYTHONPATH: $PYTHONPATH:/usr/lib/python3/dist-packages:/usr/local/lib/python3/dist-packages
       
    steps:
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: noetic
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros1-distro: noetic
      - name: Install CRAM dependencies
        run: |
          sudo apt-get install -y python3-wstool
          export WS_PATH=${{ steps.action_ros_ci_step.outputs.ros-workspace-directory-name }}
          echo "Workspace path: $WS_PATH"
          echo "CI source path: $CI_SOURCE_PATH"
          echo "Current path: $(pwd)"
          cd $WS_PATH
          source devel/setup.bash
          cd src
          wstool init
          wstool merge ./cram/cram-20.04.rosinstall
          wstool update
          cd ..
          catkin_make
          source devel/setup.bash
          echo "Cram Tests location: $(rospack find cram_tests)"
          rosrun cram_tests test.sh
