# This is a basic workflow to help you get started with Actions

name: CI

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    env:
      ROS_DISTRO: noetic # only useful in run-sections
      ROSINSTALL_FILE: https://raw.githubusercontent.com/cram2/cram/devel/cram-20.04-http.rosinstall
       
    steps:
      - name: Build ROS
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: noetic
          
      - name: Install CRAM rosdeps and build workspace
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros1-distro: noetic
          vcs-repo-file-url: ${{ env.ROSINSTALL_FILE }}
          
#       - name: Create rosinstall file
#         run: |
#           sudo apt-get install -y python3-wstool tree
#           cd ros_ws/src
#           wstool init
#           # echo "GITHUB WORKSPACE: "
#           # echo $GITHUB_WORKSPACE
#           wstool merge $ROSINSTALL_FILE
#           wstool rm cram
#           cp .rosinstall /tmp/deps.repos
          
#       - name: Pull rosinstall repositories
#         uses: ros-tooling/action-ros-ci@v0.2
#         with:
#           target-ros1-distro: noetic
#           vcs-repo-file-url: /tmp/deps.repos
          
      - name: Execute CRAM Tests
        run: |
          pwd
          tree -L 4
          cd $GITHUB_WORKSPACE
          tree -L 4
          echo "GITHUB WORKSPACE: "
          echo $GITHUB_WORKSPACE       
          source $GITHUB_WORKSPACE/ros_ws/devel/setup.bash
          echo "---BEGIN TESTS---"
          # /usr/bin/sbcl --non-interactive --eval "(print \"Hello\")"          
          rosrun cram_tests test.sh



# ---

#          /usr/bin/sbcl --non-interactive --eval "(progn (load (parse-namestring (concatenate 'string (sb-ext:posix-getenv \"ROS_ROOT\") \"lisp/scripts/roslisp-sbcl-init\"))) (asdf:load-system :cram-pr2-pick-place-demo))" --quit
#          export WS_PATH=${{ steps.action_ros_ci_step.outputs.ros-workspace-directory-name }}
#          echo "Workspace path: $WS_PATH"
#          echo "CI source path: $CI_SOURCE_PATH"
#          echo "Current path: $(pwd)"
#          source devel/setup.bash
#          cd src
#          wstool init
#          wstool merge ./cram/cram-20.04.rosinstall
#          wstool update
#          cd ..
#          catkin_make
#          source devel/setup.bash
#          echo "Cram Tests location: $(rospack find cram_tests)"
#          rosrun cram_tests test.sh
